sudo: required
services:
  - docker

before_install:
  - docker build -t robihdy/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run robihdy/client-test npm run test -- --watchAll=false

after_success:
  - docker build -t robihdy/jr-swe-client ./client
  - docker build -t robihdy/jr-swe-api ./api
  - docker build -t robihdy/jr-swe-worker ./worker
  - docker build -t robihdy/jr-swe-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push robihdy/jr-swe-client
  - docker push robihdy/jr-swe-api
  - docker push robihdy/jr-swe-worker
  - docker push robihdy/jr-swe-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: jr-swe
  env: JrSwe-env
  bucket-name: elasticbeanstalk-us-east-2-353969886337
  bucket-path: jr-swe
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
